name: CI for test the remove function
on:
  push:
    branches:
      - Vignaud/script_remove_data
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Remove psql 14
        run: sudo apt-get --purge remove postgresql postgresql-14
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name : Install extension 
        run : sudo apt-get install postgresql-plpython3-12 postgis postgresql-12-postgis-3
      - name: Start PostgreSQL on Ubuntu
        run: sudo systemctl start postgresql.service
      - name : Service ready ?
        run: pg_isready
      - name: Create test user
        run: sudo -u postgres psql --command="CREATE USER test PASSWORD 'test'" --command="\du"
      - name: Create test database
        run: sudo -u postgres createdb --owner=test test 
      - name: Connect to the database
        run: PGPASSWORD=test psql --username=test --host=localhost --list test
      - name : CREATE EXTENSION
        run : psql postgres -h localhost -d test -c 'CREATE EXTENSION plpython3u'
        env:
          PGPASSWORD: test
#      - name : Instance the remove function
#        run : psql postgres -h localhost -d alegoria -f BDD/script_implement/remove_data.sql
#        env:
#          PGPASSWORD: postgres 