name: Maven test
on:
  push:
    branches:
      - Vignaud_Mohad/BDD_creation
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: alegoria
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name: Install Postgis
        run: sudo apt install postgis postgresql-12-postgis-3
      - name : Install pip
        run : sudo apt-get install python3-pip 
      - name : Install libray
        run: pip install psycopg2-binary
      - name : Fill database
        run : python3 BDD/script_implement/create_BDD.py postgres postgres alegoria localhost 5432