name: CI for test the database
on:
  push:
    branches:
      - Vignaud/script_remove_data
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:12-3.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: alegoria
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
#      - name : Install pip
#        run : sudo apt-get install python3-pip 
#      - name : Install library
#        run: pip install psycopg2-binary
#      - name : Fill database
#        run : python3 BDD/script_implement/create_BDD.py postgres postgres alegoria localhost 5432
#      - name : Remove a data
#        run : python3 BDD/script_implement/create_BDD.py postgres postgres alegoria localhost 5432 points_appuis 0
#      - name : Do all tests
#        run : python3 BDD/script_implement/test/test_create_BDD.py
      - name : Install python extension for postgresql
        run : sudo apt-get install postgresql-plpython3-12
      - name : restart the database
        run : sudo pg_ctlcluster 12 main start
      - name : CREATE EXTENSION
        run : psql postgres -h localhost -d alegoria -c 'CREATE EXTENSION plpython3u'
        env:
          PGPASSWORD: postgres
      - name : Instance the remove function
        run : psql postgres -h localhost -d alegoria -f BDD/script_implement/remove_data.sql
        env:
          PGPASSWORD: postgres 